Primeiro exemplo de programa

In [ ]:
# comentário
print('Oi')
"""
Comentário
de várias linhas
"""

Oi


Início do curso de reforço

Dados x informação

temperatura - 22°C

Tipos de dados
inteiro
real

1.5

moeda     0.89

Texto - 'texto'
        "texto"

Booleano

Complexo



In [ ]:
1 > 2

False

Inteiros

In [ ]:
1_000_000_000
1234
0
-10000

-10000

Base 2

In [ ]:
0b111111111

511

Base 8

In [ ]:
0o7654

4012

Base 16

In [ ]:
0xCAFE

51966

Números reais

In [ ]:
123.56
.5
6.02E23
1E100

6.02e+23

Números complexos

In [ ]:
(1 + 2j)

(1+2j)

Leitura e impressão

In [ ]:
entrada = input('digite seu nome:')
print(entrada)


digite seu nome:teste
teste


Variável: parte da memória associada a um tipo e nome

In [ ]:
x = 10
y = 1.5
z = 'texto'

Operadores:
Básicos:
+ - * /
//

In [ ]:
print( 1/2 )
print( 1//2 )
print( 7//2 )
print( 7 % 2 )

0.5
0
3
1


In [ ]:
idade = int(input('Digite sua idade: '))
print(2025 - idade)

Digite sua idade: 30
1995


In [ ]:
ano = int(input("digite ano de nascimento:")) # entrada
idade = 2025-ano                              #cálculo
print(idade)                                  #saída


digite ano de nascimento:1980
45


In [ ]:
peso = float(input("Digite seu peso: "))
altura = float(input("Digite sua altura: "))
imc = peso / (altura*altura)
print(imc)

Digite seu peso: 70
Digite sua altura: 1.7
24.221453287197235


Dadas duas variáveis x e y, trocar seus valores

In [ ]:
x = 1
y = 2
temp = x
x = y
y = temp
print(x, y)

2 1


Operdores de comparação e lógicos:


< <= > >= != == **
and
or
not


In [ ]:
1 < 2

True

In [ ]:
2 ** 10

1024

In [ ]:
not ( 1 < 2 )

False

Fazer um programa que lê a sua idade e diz se você pode dirigir

In [ ]:
idade = int(input("Digite sua idade: "))
if idade >= 18:
  print("você é maior e pode dirigir")
print("fim")

Digite sua idade: 15
fim


In [ ]:
idade = int(input("Digite sua idade: "))
if idade >= 18:
  print("você é maior e pode dirigir")
else:
  print("você é menor e não pode dirigir")
print("fim")

Digite sua idade: 10
você é menor e não pode dirigir
fim


In [ ]:
peso = float(input("Digite seu peso: "))
altura = float(input("Digite sua altura: "))
imc = peso / (altura*altura)
print(imc)
if imc < 18.5:
  print("Magro")
elif imc < 25:
  print("Normal")
elif imc < 30:
  print("Sobrepeso")
else:
  print("Obeso")
print("mais uma linha")

Digite seu peso: 100
Digite sua altura: 1.7
34.602076124567475
Obeso
mais uma linha


Dados dois números inteiros, imprimir na ordem crescente

In [ ]:
a = int( input("digite o 1o número"))
b = int( input("digite o 2o número"))
if a < b:
  print(a, b)
else:
  print(b, a)

digite o 1o número10
digite o 2o número20
10 20


dados 3 números, imprimir em ordem crescente:
```
a b c
a c b
b a c
b c a
c a b
c b a
```


In [ ]:
a = int( input("digite o 1o número:"))
b = int( input("digite o 2o número:"))
c = int( input("digite o 3o número:"))

if ( a <= b and b <= c ):
  print(a, b, c)
elif ( a <= c and c <= b ):
  print(a, c, b)
elif (b <= a and a <= c ):
  print(b, a, c)
elif (b <= c and c <= a ):
  print(b, c, a)
elif (c <= a and a <= b ):
  print(c, a, b)
else:
  print(c, b, a)

digite o 1o número:3
digite o 2o número:2
digite o 3o número:1
1 2 3


Dados 3 números reais, dizer se eles formam um triângulo retângulo

In [ ]:
a = float( input("digite o 1o número:"))
b = float( input("digite o 2o número:"))
c = float( input("digite o 3o número:"))
if a*a + b*b == c*c or a*a + c*c == b*b or b*b + c*c == a*a:
  print("triângulo retângulo")
else:
  print("não é triângulo retângulo")

digite o 1o número:4
digite o 2o número:3
digite o 3o número:5
triângulo retângulo


In [ ]:
x = 0.1239

print(f'o valor de x é {x:.3f} texto')

o valor de x é 0.124 texto


In [ ]:
a = int( input("digite o 1o número:"))
b = int( input("digite o 2o número:"))
c = int( input("digite o 3o número:"))

print(f'o valor de a é {a}, o valor de b é {b} , o valor de c é {c}')

digite o 1o número:2
digite o 2o número:3
digite o 3o número:4
o valor de a é 2, o valor de b é 3 , o valor de c é 4


In [ ]:
A = int(input())
B = int(input())
X = A + B
print(f'X = {X}')

2
3
X = 5


In [ ]:
pi = 3.14159
raio = float(input())
area = pi * raio ** 2
print(f'A={area:.4f}')

2
A=12.5664


In [ ]:
x, y, z = 1,2,3
print(x,y,z)

1 2 3


In [ ]:
nome, nomeDoMeio, sobreNome = 'Eugênio', 'Akihiro', 'Nassu'
print(f'{nome} {nomeDoMeio} {sobreNome}')

Eugênio Akihiro Nassu


In [ ]:
codigo, quantidade, preco = input().split()
print(codigo)
print(quantidade)
print(preco)

12 1 5.3
12
1
5.3


In [ ]:
nome, nomeDoMeio, sobreNome = input().split()
print(nome)
print(nomeDoMeio)
print(sobreNome)

Eugênio Akihiro Nassu
Eugênio
Akihiro
Nassu


In [ ]:
codigo, quantidade, preco = input().split()
codigo = int(codigo)
quantidade = int(quantidade)
preco = float(preco)
codigo1, quantidade1, preco1 = input().split()
codigo1 = int(codigo1)
quantidade1 = int(quantidade1)
preco1 = float(preco1)
valor = quantidade * preco + quantidade1 * preco1
print(f'VALOR A PAGAR: R$ {valor:.2f}')


12 1 5.30
16 2 5.10
VALOR A PAGAR: R$ 15.50


Operadores avançados


```
AND Bit a bit - &

0B101011101
0B110100001
--------------
0B100000001

OR Bit a bit - |

0B101011101
0B110100001
--------------
0B111111101

OR exclusivo (XOR) - ^
0B101011101
0B110100001
--------------
0B011111100

0B101010111 >> 3
0B101010111 << 3


In [ ]:
print( bin(0B101011101 & 0B110100001))
print( bin(0B101011101 | 0B110100001))
print( bin(0B101011101 ^ 0B110100001))
print( 0B101011101 ^ 0B110100001)
print( bin(0B101010111 >> 3))
print( bin(0B101010111 << 5))

0b100000001
0b111111101
0b11111100
252
0b101010
0b10101011100000




```
Atribuição com operdor:
+=
-=
*=
/=
//=
%=
**=
>>=
<<=
&=
|=
^=

```



In [ ]:
x = 0
x += 2

x &= 2

range: definição de intervalos



```
range( <início>, <limite>, <incremento> )
```


início - opcional, padrão 0
incremento, opcional, padrão 1
```
exemplos:
range(10) - 0 1 2 3 4 5 6 7 8 9
range(1,11) - 1 2 3 4 5 6 7 8 9 10
range(0, 11, 2) - 0 2 4 6 8 10
```
comando for é bastante comum com o range

for - usado quando precisamos repetir um comando e a quantidade de repetições é conhecida



In [ ]:
# imprimir o nome digitado 10 vezes

nome = input("digite seu nome")
for i in range(10):
  print(f'{nome} {i} vezes')

digite seu nomeEugênio
Eugênio 0 vezes
Eugênio 1 vezes
Eugênio 2 vezes
Eugênio 3 vezes
Eugênio 4 vezes
Eugênio 5 vezes
Eugênio 6 vezes
Eugênio 7 vezes
Eugênio 8 vezes
Eugênio 9 vezes


In [ ]:
# imprimir números de 1 a 5
for n in range(1,6):
  print(n)

1
2
3
4
5


In [ ]:
# diz se um número é par ou ímpar (números de 0 a 10)

for n in range(11):
  if( n % 2 == 0 ):
    print(f'{n} é par')
  else:
    print(f'{n} é ímpar')

0 é par
1 é ímpar
2 é par
3 é ímpar
4 é par
5 é ímpar
6 é par
7 é ímpar
8 é par
9 é ímpar
10 é par


Dado um número n, imprimir sua tabuada

In [ ]:
n = int( input('digite n:') )
for i in range(1,11):
  print(f'{n:2} x {i:2} = {n*i:2}')

digite n:13
13 x  1 = 13
13 x  2 = 26
13 x  3 = 39
13 x  4 = 52
13 x  5 = 65
13 x  6 = 78
13 x  7 = 91
13 x  8 = 104
13 x  9 = 117
13 x 10 = 130


Faça um programa que lê 5 números, imprimindo a soma de todos os números no final

soma é uma variável acumuladora

In [ ]:
soma = 0
for i in range(5):
  n = int( input('digite o número:'))
  soma = soma + n

print(f'a soma dos números é {soma}')

digite o número:1
digite o número:2
digite o número:3
digite o número:4
digite o número:5
a soma dos números é 15


Faça um programa que lê 5 números e imprime qual deles é o maior

In [ ]:
n = int( input('digite um número:') )
maior = n;
for i in range(4):
  n = int( input('digite um número:') )
  if n > maior:
    maior = n

print(f'o maior número é {maior}')

digite um número:-1
digite um número:3
digite um número:0
digite um número:4
digite um número:2
o maior número é 4


Dadas as notas de prova de 10 alunos, imprimir qual foi a média das notas

In [ ]:
print('digite 10 notas:')
soma = 0
for i in range(10):
  nota = float(input("nota:"))
  soma += nota
media = soma / 10
print(f'a média é {media:.1f}')

digite 10 notas:
nota:7
nota:6
nota:4
nota:9
nota:8
nota:10
nota:4
nota:0
nota:1
nota:4
a média é 5.3


2.  Dado um número inteiro positivo n, calcular a soma dos n primeiros números inteiros positivos.

In [ ]:
n = int( input('digite n:'))
soma = 0
for i in range(n+1):
  soma += i
print(f'a soma é {soma}')

digite n:999
a soma é 499500


1    2    3    4    ....      498  499 500
1000 999  998  997            503  502 501
----------------------------------------
1001 1001 1001 1001          1001 1001 1001

1001 * 500 = 500500

(n + 1) * n / 2

In [ ]:
n = int( input('digite n:'))
soma = (n+1) * n / 2
print(f'a soma é {soma}')

digite n:999
a soma é 499500.0


In [ ]:
# exemplo: cálculo do fatorial de n
n = int(input('digite n:'))
fatorial = 1
for i in range(1,n+1):
  fatorial *= i
print(f'{n}! = {fatorial}')

digite n:50
50! = 30414093201713378043612608166064768844377641568960512000000000000


Dados dia, mês e ano, dizer se eles formam uma data válida

9
4
2025
data válida

ano bissexto - (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0)

In [ ]:
dia = int( input('digite o dia:'))
mes = int( input('digite o mês:'))
ano = int( input('digite o ano:'))
dataValida = True
if( mes >= 1 and mes <= 12 ):
  if mes == 1 or mes == 3 or mes == 5 or mes == 7 or mes == 8 or mes == 10 or mes == 12:
    if ( dia < 1 or dia > 31 ):
      dataValida = False
  elif mes == 4 or mes == 6 or mes == 9 or mes == 11:
    if ( dia < 1 or dia > 30 ):
      dataValida = False
  elif  (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
    if ( mes == 2 and (dia < 1 or dia > 29)):
      dataValida = False
  elif ( mes == 2 and (dia < 1 or dia > 28)):
    dataValida = False
else:
  dataValida = False

if ( dataValida ):
  print('data válida')
else:
  print('data inválida')

digite o dia:1
digite o mês:4
digite o ano:2000
data válida


while - número indefinido de repetições

exemplo: problema da lista macmulti 1

In [ ]:
n = int( input('digite um número:'))
while n != 0:
  print( n*n )
  n = int(input('digite um número:'))

digite um número:1
1
digite um número:3
9
digite um número:5
25
digite um número:3
9
digite um número:7
49
digite um número:10
100
digite um número:1000
1000000
digite um número:3
9
digite um número:-1
1
digite um número:-9
81
digite um número:18
324
digite um número:20
400
digite um número:0


Dados dois números inteiros positivos, x e y, calcule x//y, mas sem utilizar o operador //
Podemos resolver este problema usando o while, a subtração

10 // 3
10 % 3

In [ ]:
x = int ( input('digite x:'))
y = int ( input('digite y:'))
quociente = 0
resto = x;
while resto >= y:
  resto -= y;
  quociente += 1
print(f'quociente = {quociente}')
print(f'resto = {resto}')

digite x:10
digite y:3
quociente = 3
resto = 1


Fazer um número de repetições fixo, ex: imprimir o nome 10 vezes com while

In [ ]:
nome = input('digite o nome:')
contador = 0
while contador < 10:
  print(nome)
  contador += 1

digite o nome:eugenio
eugenio
eugenio
eugenio
eugenio
eugenio
eugenio
eugenio
eugenio
eugenio
eugenio


número triangular: produto de 3 números inteiros positivos

Dado n, verificar se ele é triangular.
```
1 * 2 * 3
2 * 3 * 4
3 * 4 * 5 ... até que o produto seja igual ou maior que n
```


In [ ]:
n = int( input('digite n:'))
i = 1
while i * (i+1) * (i+2) < n:
  i += 1
if n == i * (i+1) * (i+2):
  print('n é triangular')
else:
  print('n não é triangular')

digite n:400
n não é triangular


Dados dois números inteiros, calcular o MDC entre eles

In [ ]:
x = int( input('digite um número:'))
y = int( input('digite outro número:'))
p = x
q = y
r = p % q
while r != 0:
  p = q
  q = r
  r = p % q
print(f'o MDC de {x} e {y} é {q}')

digite um número:24
digite outro número:18
o MDC de 24 e 18 é 6


Número perfeito: igual a soma de seus divisores menores que ele mesmo:
exemplo: 6 = 1 + 2 + 3
dado n, verificar se ele é perfeito

In [ ]:
n = int( input('digite n:'))
soma = 0;
divisor = 1;
while divisor <= n//2:
  if n % divisor == 0:
    soma += divisor
  divisor += 1
if soma == n:
  print('número perfeito!')
else:
  print('não é perfeito!')

digite n:33550336
número perfeito!


problema 20 da lista Macmulti

00 00 = 0
00 01 = 1
20 25 = 45 * 45 = 2025
30 25 = 55 * 55 = 3025
98 01 = 99 * 99 = 9801

In [ ]:
for n in range(10000):
  x = n % 100
  y = n // 100
  if (x+y)**2 == n:
    print(n)

0
1
2025
3025
9801


resolver o exercício 1059 - imprimir os números pares entre 1 e 100 (inclusive)

In [ ]:
for n in range(1, 101):
  if n % 2 == 0:
    print(n)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [ ]:
for n in range(2, 101, 2):
  print(n)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


problema 1060 beecrowd:

In [ ]:
contador = 0
for i in range(6):
  x = float(input())
  if x > 0:
    contador += 1
print(f'{contador} valores positivos')

7
-5
6
-3.4
4.6
12
4 valores positivos


problema 1072 beecrowd

In [ ]:
n = int(input())
contin = 0
for i in range(n):
  x = int(input())
  if x >= 10 and x <= 20:
    contin += 1
contout = n - contin
print(f'{contin} in')
print(f'{contout} out')

In [ ]:
# break interrompe o comando for
for n in range(100):
  print(n)
  if n == 50:
    break

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [ ]:
for n in range(10):
  if n % 2 == 0:
    continue
  print(n)

1
3
5
7
9


In [ ]:
for n in range(5):
  print(n)
else:
  print('acabou o for')

0
1
2
3
4
acabou o for


In [ ]:
cont = 0;
while cont < 5:
  print(cont)
  cont += 1
else:
  print('fim do while')

0
1
2
3
4
fim do while


Aula de 16/4 - Tipos compostos
Tuplas
Listas
dicionário
conjunto
vetores e matrizes

In [ ]:
t = (1, 9, 3.14, 'aula')
tuplaVazia = ()
print( t[0] )
print(t[1:3]) # intervalo a partir do índice 1 e com índice menor que 3
print(t[2:])
# t[0] = 0 #dá erro pois não é permitido alterar o valor de um elemento da tupla

1
(9, 3.14)
(3.14, 'aula')


In [ ]:
tAeroportos = ('JFK', 'GRU', 'CGN', 'CDG', 'KLA', 'KAT')
print(tAeroportos[3:])
print(tAeroportos[1:4])

('CDG', 'KLA', 'KAT')
('GRU', 'CGN', 'CDG')


In [ ]:
aluno = (1111, 'José', '10/05/2000', 1.7)

Conjuntos - valores entre chaves {}

In [ ]:
conjunto = {1, 2, 'três', 'quatro', 5}
conjunto3 = { 1, 5, 7 }
print(len(conjunto))

print( 1 in conjunto )
print( 0.5 in conjunto )

conjunto2 = conjunto | {6} # união

print(conjunto2)

print(conjunto & conjunto3)

print(conjunto - conjunto3)

print( conjunto > {1,2} )
print({1,2} < conjunto )
conjunto.pop() #exclui um elemento

print(conjunto)
print(conjunto <= conjunto)



5
True
False
{1, 2, 'quatro', 'três', 5, 6}
{1, 5}
{2, 'quatro', 'três'}
True
True
{2, 'quatro', 'três', 5}
True


Dicionário: funciona como conjunto em que elementos tem uma chave para que sejam recuperados

In [ ]:
d = {5:10, 3:'aaa', 'teste': 123, 'aaa': 'aaa'}

print(d['teste'])

print(d.keys())
print(d.values())

for chave in d.keys():
  print(d[chave])

123
dict_keys([5, 3, 'teste', 'aaa'])
dict_values([10, 'aaa', 123, 'aaa'])
10
aaa
123
aaa


In [ ]:
notas = [4.0, 7, 8, 9, 10]

notas = notas + [5]

print(notas)

print(notas[0])
print(notas[1])
print(notas[3])

for i in range(len(notas)):
  print(notas[i])

[4.0, 7, 8, 9, 10, 5]
4.0
7
9
4.0
7
8
9
10
5


Dados n números inteiros, imprimir na ordem inversa da leitura

In [ ]:
n = int( input('digite n:') )
v = []
for i in range(n):
  x = int(input('digite um número:'))
  v = v + [x]

for i in reversed(range(n)):
  print(v[i])


digite n:5
digite um número:1
digite um número:2
digite um número:3
digite um número:4
digite um número:5
5
4
3
2
1


Dados o gabarito de uma prova de 5 questões, o número de alunos e os cartões resposta de cada um, imprima o número de acertos de cada um

In [ ]:
gabarito = ['A','B','C','D','E']
n = int(input('digite o número de alunos'))
for i in range(n):
  respostas = ['A','B','C','D','E']
  print('digite as respostas:')
  acertos = 0
  for j in range(len(respostas)):
    print(f'resposta questão {j}:')
    respostas[j] = input()
    if respostas[j] == gabarito[j]:
      acertos += 1
  print(f' aluno acertou {acertos}')

digite o número de alunos3
digite as respostas:
resposta questão 0:
A
resposta questão 1:
A
resposta questão 2:
A
resposta questão 3:
A
resposta questão 4:
A
 aluno acertou 1
digite as respostas:
resposta questão 0:
A
resposta questão 1:
B
resposta questão 2:
A
resposta questão 3:
A
resposta questão 4:
A
 aluno acertou 2
digite as respostas:
resposta questão 0:
A
resposta questão 1:
B
resposta questão 2:
C
resposta questão 3:
D
resposta questão 4:
E
 aluno acertou 5


In [ ]:
n = int(input('digite n:'))
v = []
for i in range(n):
  r = int(input())
  v = v + [r]
resultados = [0,0,0,0,0,0,0]
for i in range(n):
  resultados[v[i]] += 1
print('frequências:')
for i in range(1,7):
  print(f'{i}: {resultados[i]} vezes')

digite n:10
1
1
1
2
2
3
4
4
4
5
frequências:
1: 3 vezes
2: 2 vezes
3: 1 vezes
4: 3 vezes
5: 1 vezes
6: 0 vezes


Beecrowd 1172

In [ ]:
X = [0,0,0,0,0,0,0,0,0,0]
for i in range(10):
  X[i] = int(input())

for i in range(10):
  if X[i] <= 0:
    X[i] = 1

for i in range(10):
  print(f'X[{i}] = {X[i]}')

-1
0
10
0
-20
3
1
3
7
9
X[0] = 1
X[1] = 1
X[2] = 10
X[3] = 1
X[4] = 1
X[5] = 3
X[6] = 1
X[7] = 3
X[8] = 7
X[9] = 9


In [ ]:
#Beecrowd 1178

N = []
v = float(input())
N = N + [v]
for i in range(1,100):
  v = N[i-1]/2
  N = N + [v]

for i in range(100):
  print(f'N[{i}] = {N[i]:.4f}')

200.0000
N[0] = 200.0000
N[1] = 100.0000
N[2] = 50.0000
N[3] = 25.0000
N[4] = 12.5000
N[5] = 6.2500
N[6] = 3.1250
N[7] = 1.5625
N[8] = 0.7812
N[9] = 0.3906
N[10] = 0.1953
N[11] = 0.0977
N[12] = 0.0488
N[13] = 0.0244
N[14] = 0.0122
N[15] = 0.0061
N[16] = 0.0031
N[17] = 0.0015
N[18] = 0.0008
N[19] = 0.0004
N[20] = 0.0002
N[21] = 0.0001
N[22] = 0.0000
N[23] = 0.0000
N[24] = 0.0000
N[25] = 0.0000
N[26] = 0.0000
N[27] = 0.0000
N[28] = 0.0000
N[29] = 0.0000
N[30] = 0.0000
N[31] = 0.0000
N[32] = 0.0000
N[33] = 0.0000
N[34] = 0.0000
N[35] = 0.0000
N[36] = 0.0000
N[37] = 0.0000
N[38] = 0.0000
N[39] = 0.0000
N[40] = 0.0000
N[41] = 0.0000
N[42] = 0.0000
N[43] = 0.0000
N[44] = 0.0000
N[45] = 0.0000
N[46] = 0.0000
N[47] = 0.0000
N[48] = 0.0000
N[49] = 0.0000
N[50] = 0.0000
N[51] = 0.0000
N[52] = 0.0000
N[53] = 0.0000
N[54] = 0.0000
N[55] = 0.0000
N[56] = 0.0000
N[57] = 0.0000
N[58] = 0.0000
N[59] = 0.0000
N[60] = 0.0000
N[61] = 0.0000
N[62] = 0.0000
N[63] = 0.0000
N[64] = 0.0000
N[65] = 0.0000
N[66

In [ ]:
#Beecrowd 1173
N = [0,0,0,0,0,0,0,0,0,0]
N[0]= int(input())
for i in range(1,10):
  N[i] = N[i-1]*2
for i in range(10):
  print(f'N[{i}] = {N[i]}')

1
N[0] = 1
N[1] = 2
N[2] = 4
N[3] = 8
N[4] = 16
N[5] = 32
N[6] = 64
N[7] = 128
N[8] = 256
N[9] = 512


Importação de bibliotecas

NumPy

In [ ]:
import numpy as np

v1 = np.array([1,2,3,4,5])
v2 = np.arange(0,10,2)
v3 = np.linspace(0,1,5)
v4 = np.linspace(0,1,6)
v5 = np.linspace(0,1,7)
v6 = np.linspace(0,1,8)
v7 = np.linspace(0,1,9)
print(v1)
print(v2)
print(v3)
print(v4)
print(v5)
print(v6)
print(v7)
v0 = np.zeros(10)
print(v0)
vones = np.ones(7)
print(vones)

vsoma = v1 + 2
print(vsoma)
vmult = v1 * 7
print(vmult)
vq = v1 ** 2
print(vq)

rq = np.sqrt(vq)

print(rq)

[1 2 3 4 5]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8 1. ]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[3 4 5 6 7]
[ 7 14 21 28 35]
[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]


In [ ]:
v3 = np.linspace(0,10,5) # 0 - início 10 - final 5 número de elementos do vetor que serão igualmente espaçad
print(v3)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


Matrizes



In [ ]:
# matriz com 3 linhas e 4 colunas:

matriz34 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9,10,11,12]])
matriz32Zeros = np.zeros((5,4))

matrizId = np.eye(3)

print(matriz34)
print(matriz32Zeros)

print(matrizId)

print(matriz34[1,2])
print(matriz34[:,1])
print(matriz34[1,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
7
[ 2  6 10]
[5 6 7 8]


multiplicação de matrizes

In [ ]:

matriz34 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9,10,11,12]])

matriz42 = np.array([[1,2],
                     [3,4],
                     [5,6],
                     [7,8]])

prod = np.dot( matriz34, matriz42 )
print(prod)

matrizT = matriz42.T

print(matrizT)

msoma = matriz34 + 1

print(msoma)

print(np.sum(matriz34))

[[ 50  60]
 [114 140]
 [178 220]]
[[1 3 5 7]
 [2 4 6 8]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
78


In [ ]:
mletras = [['a','b','c'],
           ['d','e','f']]
print(mletras)
mletras[1][2]

[['a', 'b', 'c'], ['d', 'e', 'f']]


'f'

```
[1, 2, 3, 4] [1,2]     [1*1+3*2+5*3+4*7,2*1+4*2+6*3+8*4]
[5, 6, 7, 8] [3,4]     [1*5+3*6+5*7+7*8,2*5+4*6+6*7+8*8]
[9,10,11,12] [5,6]  =  [1*9+3*10+5*11+7*12,2*9+4*10+6*11+8*12]
             [7,8]

```
3 x 4 - 4 x n = 3 x n
para cada elemento p[i,j] = somatória com k = 0 até n de m1[i,k]*[k,j]

In [ ]:
matriz34 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9,10,11,12]])

matriz42 = np.array([[1,2],
                     [3,4],
                     [5,6],
                     [7,8]])


m = 3
n = 4
p = 2
produto = np.zeros((m,p))
for i in range(m):
  for j in range(p):
    for k in range(n):
      produto[i,j] += matriz34[i,k]*matriz42[k,j]

print(produto)

[[ 50.  60.]
 [114. 140.]
 [178. 220.]]


In [ ]:
#dada uma matriz m x n, verificar se há números repetidos

m = int(input('digite número de linhas:'))
n = int(input('digite número de colunas:'))

matriz = np.zeros((m,n))
p = m*n
print(f'digite os {p} elementos da matriz:')
for i in range(m):
  for j in range(n):
    print(f'elemento matriz[{i},{j}]')
    matriz[i,j] = int(input())

for i in range(m):
  for j in range(n):
    for i1 in range(m):
      for j1 in range(n):
        if ( (i != i1 and j != j1) and matriz[i,j] == matriz[i1,j1]):
          print( f'{matriz[i,j]} se repete')
          quit()

print(matriz)

digite número de linhas:3
digite número de colunas:3
digite os 9 elementos da matriz:
elemento matriz[0,0]
1
elemento matriz[0,1]
2
elemento matriz[0,2]
3
elemento matriz[1,0]
4
elemento matriz[1,1]
5
elemento matriz[1,2]
1
elemento matriz[2,0]
7
elemento matriz[2,1]
8
elemento matriz[2,2]
9
1.0 se repete
1.0 se repete
[[1. 2. 3.]
 [4. 5. 1.]
 [7. 8. 9.]]


In [ ]:
#problema 5 macmulti: Dada uma matriz nxn de inteiros, verificar se ela é de permutação
import numpy as np

n = int(input('digite dimensão da matriz:'))
matriz = np.zeros((n,n))
p = n*n
print(f'digite os {p} elementos da matriz:')
for i in range(n):
  for j in range(n):
    print(f'elemento matriz[{i},{j}]')
    matriz[i,j] = int(input())
permutacao = True
for i in range(n):
  contazero = 0
  contaum = 0
  for j in range(n):
    if matriz[i,j] == 1:
      contaum += 1
    if matriz[i,j] == 0:
      contazero += 1
  if contazero != n-1 and contaum != 1:
    permutacao = False

for i in range(n):
  contazero = 0
  contaum = 0
  for j in range(n):
    if matriz[j,i] == 1:
      contaum += 1
    if matriz[j,i] == 0:
      contazero += 1
  if contazero != n-1 and contaum != 1:
    permutacao = False

if permutacao:
  print('é permutação')
else:
  print('não é permutação')

# 0 0 1
# 1 0 0
# 0 1 0

digite dimensão da matriz:3
digite os 9 elementos da matriz:
elemento matriz[0,0]
1
elemento matriz[0,1]
0
elemento matriz[0,2]
0
elemento matriz[1,0]
1
elemento matriz[1,1]
0
elemento matriz[1,2]
0
elemento matriz[2,0]
1
elemento matriz[2,1]
0
elemento matriz[2,2]
0
não é permutação


In [ ]:
matriz3d = np.array([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[10,11,12],
                      [13,14,15],
                      [16,17,18]],
                     [[19,20,21],
                      [22,23,24],
                      [25,26,27]]])

print(matriz3d[0,1,2])

6


In [ ]:
#problema 1181

linha = int(input())
op = input()
soma = 0;
m =[]
for i in range(12):
  m.append([])
  for j in range(12):
    x = float(input())
    m[i].append(x)
    if i == linha:
      soma += x
if op == 'S':
  print(f'{soma:1.f}')
else:
  media = soma/12
  print(f'{media:.1f}')

Subprogramas:
Quando um trecho de programa é repetido de forma recorrente, podemos criar uma função ou procedimento. Uma função resulta em um valor, enquanto um procedimento apenas executa algum código, sem um resultado.

In [1]:
def procedimento():
  print("Executado de um procedimento")

procedimento()

Executado de um procedimento


In [3]:
def dobro( x ):
  return x * 2

y = dobro(3)

print(y)

6


In [4]:
def oi(nome):
  print(f'Olá {nome}')

oi('Eugênio')

Olá Eugênio


In [6]:
def calcularImc(peso, altura):
  return peso/(altura*altura)

peso = float(input('digite o peso:'))
altura = float(input('digite a altura:'))
imc = calcularImc(peso, altura)
print(f'o IMC é {imc:.2f}')

digite o peso:70
digite a altura:1.65
o IMC é 25.71


In [8]:
import math

def calcularAreaCirculo(raio):
  area = math.pi * raio ** 2
  return area

r = float(input('digite o raio:'))
a = calcularAreaCirculo(r)
print(f'a área do círculo com raio {r} é {a}')

digite o raio:3
a área do círculo com raio 3.0 é 28.274333882308138




1

In [19]:
#Macmulti exercícios com funções 1

def contaDigitos( n, d ):
  q = n
  cont = 0
  while q > 0:
    digito = q % 10
    if digito == d:
      cont += 1
    q //= 10
  return cont

x = int(input('digite x:'))
y = int(input('digite y:'))

permutacao = True
for d in range(1,10):
  if contaDigitos(x, d) != contaDigitos(y, d):
    permutacao = False
    break

if permutacao:
  print(f'{x} é permutação de {y}')
else:
  print(f'{x} não é permutação de {y}')

digite x:12345
digite y:32145
12345 é permutação de 32145


In [27]:
#Macmulti problemas com funções - 2

def encaixa(a, b):
  while b != 0 and a%10 == b%10:
    a //= 10
    b //= 10
  return b == 0

x = int(input('digite x:'))
y = int(input('digite y:'))

if x < y: # x sempre será o número maior
  aux = x
  x = y
  y = aux
maior = x
menor = y
segmento = False
while maior >= menor:
  if encaixa(maior,menor):
    segmento = True
  maior //= 10
if segmento:
  print(f'{y} é segmento de {x}')
else:
  print(f'{y} não é segmento de {x}')

digite x:3
digite y:243
3 é segmento de 243


In [38]:
#Macmulti problemas com funções - 5

def ehPrimo(n):
  for i in range(2,n):
    if n % i == 0:
      return False
  return True

n = int(input('digite n:'))

cont = 0
soma = 0
p = 2
while cont < n:
  if ehPrimo(p):
    print(p)
    soma += p
    cont += 1
  p += 1

print(soma)


digite n:20
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
639


Lambda é uma função definida dentro da atribuição

In [39]:
x = lambda a: a + 1

print( x(3) )

4


In [40]:
soma = lambda a,b: a + b
print( soma( 10, 20 ))

30


In [41]:
def multiplicador(n):
  return lambda a: a * n

dobro = multiplicador(2)
triplo = multiplicador(3)

print( dobro(10) )
print( triplo(10) )

20
30


Exemplo de uso de recursão

In [1]:
def fatorial(n):
  if n == 0 or n == 1:
    return 1
  else:
    return fatorial(n-1)*n

print(fatorial(20))




2432902008176640000


Recursão é quando uma função faz uma chamada para ela mesma
Se for feita sem querer, normalmente provoca um loop infinito
Cuidado com a recursão indireta, como abaixo:

In [ ]:
def f():
  g()

def g():
  h():

def h():
  f():


